/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ChatHeader: typeof import('./src/components/index/ChatHeader.vue')['default']
    ContactList: typeof import('./src/components/index/ContactList.vue')['default']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    EmojiPicker: typeof import('./src/components/emoji/EmojiPicker.vue')['default']
    InputBar: typeof import('./src/components/index/InputBar.vue')['default']
    IntimacyBondNotification: typeof import('./src/components/intimacy/IntimacyBondNotification.vue')['default']
    IntimacyExpTip: typeof import('./src/components/intimacy/IntimacyExpTip.vue')['default']
    IntimacyInteraction: typeof import('./src/components/intimacy/IntimacyInteraction.vue')['default']
    IntimacyLevelUpModal: typeof import('./src/components/intimacy/IntimacyLevelUpModal.vue')['default']
    IntimacyPanel: typeof import('./src/components/intimacy/IntimacyPanel.vue')['default']
    MessageItem: typeof import('./src/components/index/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/index/MessageList.vue')['default']
    RoomList: typeof import('./src/components/index/RoomList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/index/Sidebar.vue')['default']
    Tabbar: typeof import('./src/components/common/Tabbar.vue')['default']
    UserCard: typeof import('./src/components/index/UserCard.vue')['default']
    VersionLog: typeof import('./src/components/common/VersionLog.vue')['default']
  }
}
